### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by Yoshi8765** [dgirgenti/soundcloud-hide-reposts#1]
This bookmarklet doesn't work anymore!

**Comment by dgirgenti** [comment]
Thanks for letting me know. Looks like they just overhauled the feed UI recently. I'll have a fix up soon!

**Comment by unformatt** [comment]
Try this bookmarklet:

```
javascript:var posts = document.querySelectorAll(".soundList__item"); for (var i=0; i < posts.length; i++){ var post = posts[i]; if (post.innerHTML.indexOf('reposted')>-1) post.remove(); }
```

**Comment by dgirgenti** [comment]
Thanks @unformatt . I had been planning on killing jQuery when I fixed this as well. Would you like to submit this as a pull request?

**Comment by unformatt** [comment]
sure!
